version: 2.1
jobs:
  build-and-deploy:
    docker:
      - image: circleci/node:14.16
    steps:
      - checkout
      - run:
          name: update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{checksum "package.json"}}
      - run:
          name: install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{checksum "package.json"}}
          paths:
            - ./node_modules
      - run:
          name: build gatsby
          command: yarn run build
      - run:
          name: deploy to github
          command: bash ./deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: /master/
