version: 2
jobs:
  deploy:
    docker:
      - image: circleci/ruby:2.4.3-node-browsers
    steps:
      - checkout
      - run: npm install
      - run: bundle install
      - run: bundle exec jekyll build
      - deploy:
          name: Deploy Release to GitHub
          command: sh deploy.sh


workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              ignore: gh-pages